blank_issues_enabled: false
contact_links:
  - name: Ask a Question / Discussion
    url: https://github.com/vapnguyen24/landing/discussions
    about: For general questions, start a discussion instead of opening an issue.
